getwd()
setwd("C:\\Users\\Nisha\\Downloads\\Compressed\\2008.csv")
myDF<-fread("2008.csv")
install.packages("data.Table")
library("data.Table")
library(data.table)
myDF<-fread("2008.csv")
dim(myDF)
head(myDF)
tail(myDF)
head(myDF$Origin)
head(myDF$Dest)
tail(myDF$Origin)
tail(myDF$Dest)
count(myDF$Origin="IND")
count(myDF$Origin->'IND')
sum(myDF$Origin=="IND")
sum(myDF$Dest=="IND")
head(myDF$Origin=="IND")
names(head(myDF$Origin=="IND"))
dimnames(head(myDF$Origin=="IND"))
head(myDF(myDF$Origin=="IND"))
head(myDF[myDF$Origin=="IND"])
sum(myDF$Dest=="ORD")
sum(myDF$Origin=="ORD")
sum((myDF$Origin=="IND")&(myDF$Dest=="ORD"))
data1<-as.data.frame(myDF$Origin=="IND")
data1
data2<-as.data.frame(myDF$Dest=="IND")
dim(data1)
drop(data1)
drop(data2)
MyOrigins<-subset.data.frame(myDF,myDF$Origin=="IND")
dim(MyOrigins)
MyDestinations<-(myDF,myDF$Dest=="IND")
MyDestinations<-subset.data.frame(myDF,myDF$Dest=="IND")
dim(MyDestinations)
head(MyOrigins)
head(MyDestinations)
sum(MyOrigins$Month=="1")
table(MyOrigins$Month)
plot(table(MyOrigins$Month))
table(MyDestinations$Month)
plot(table(MyDestinations$Month))
DeparturefromTUP<-subset.data.frame(myDF,myDF$Origin=="TUP")
dim(DeparturefromTUP)
sum(DeparturefromTUP$Dest=="TUP")
nrow(DeparturefromTUP)
mean(DeparturefromTUP$DepDelay)
nrow(DeparturefromTUP)
sum(MyOrigins$DepTime<600)
sum(MyOrigins$DepTime<600,na.rm = TRUE)
sum(MyOrigins$DepTime<1200,na.rm = TRUE)
sum(MyOrigins$DepTime<1800,na.rm = TRUE)
sum(MyOrigins$DepTime<2400,na.rm = TRUE)
sum(is.na(myDF$DepTime))
sum(is.na(MyOrigins$DepTime))
sum(myDF$Origin=="IND")
sum((MyOrigins$DepTime<2400),(is.na(MyOrigins$DepTime)))
sum((MyOrigins$DepTime<2400)&(is.na(MyOrigins$DepTime)))
sum((MyOrigins$DepTime<2400)&&(is.na(MyOrigins$DepTime)))
sum(myDF$Dest=="LAX")
sum((MyOrigins$DepTime<2400 & is.na(MyOrigins$DepTime)))
sum((MyOrigins$DepTime<2400 & is.na(MyOrigins$DepTime))
sum(MyOrigins$DepTime<2400 & is.na(MyOrigins$DepTime)
(MyOrigins$DepTime<2400 & is.na(MyOrigins$DepTime)
sum(myDF$Origin=="ATL" & myDF$Dest=="LAX")
sum(myDF$Origin=="ATL" & myDF$Dest=="LAX")
sum(MyOrigins$DepTime<2400 & is.na(MyOrigins$DepTime)
sum(myDF$Dest=="LAX")
FlightATLtoLAX<-subset.data.frame(myDF,(myDF$Origin=="ATL") & (myDF$Dest=="LAX"))
sum(FlightATLtoLAX$DepTime<1200)
sum(FlightATLtoLAX$DepTime<1200,na.rm = TRUE)
table(myDF$Origin)
table(myDF$Origin,decreasing=TRUE)
sort(table(myDF$Origin),decreasing=TRUE)
FlightATLtoLAX<-subset.data.frame(myDF,(myDF$Origin=="ATL") & (myDF$Dest=="LAX"))
sum(myDF$Dest=="LAX")
myDF$Distance
head(sort(myDF$Distance),decreasing=TRUE)
head(sort(myDF$Origin),decreasing=TRUE)
head(sort(table(myDF$Origin)),decreasing=TRUE)
head(sort(table(myDF$Origin),decreasing= TRUE))
?seq
table(myDF$DepTime)
seq(table(myDF$DepTime),0,2400,by=100
seq(table(myDF$DepTime),0,2400,by=100
?cut
plot(table(cut(myDF$DepTime), breaks =seq(0,2400,by=100))
plot(table(cut(myDF$DepTime, breaks =seq(0,2400,by=100))
plot(table(cut(myDF$DepTime, breaks =seq(0,2400,by=100))
plot(table(cut(myDF$DepTime, breaks =seq(0,2400,by=100))
plot(table(cut(myDF$DepTime, breaks =seq(0,2400,by=100))))
table(paste(myDF$Origin "to" myDF$Dest))
table(paste(myDF$Origin, "to",myDF$Dest))
sort(table(paste(myDF$Origin, "to",myDF$Dest)),decreasing=TRUE)
head(sort(table(paste(myDF$Origin, "to",myDF$Dest)),decreasing=TRUE))
tail(sort(table(paste(myDF$Origin, "to",myDF$Dest)),decreasing=TRUE))
tail(sort(table(paste(myDF$Origin, "to",myDF$Dest)),decreasing=TRUE),20)
sort(table(paste(myDF$Origin, "to",myDF$Dest)==1),decreasing=TRUE)
sum(table(paste(myDF$Origin, "to",myDF$Dest)==1),decreasing=TRUE)
sum(table(paste(myDF$Origin, "to",myDF$Dest)==1))
sum(table(paste(myDF$Origin, "to",myDF$Dest))==1)
print(tapply(myDF$DepDelay,myDF$Origin,mean,na.rm=TRUE))
print(head(tapply(myDF$DepDelay,myDF$Origin,mean,na.rm=TRUE)))
print(tail(tapply(myDF$DepDelay,myDF$Origin,mean,na.rm=TRUE)))
print(tail(tapply(myDF$ArrDelay,myDF$Origin,mean,na.rm=TRUE)))
print(head(tapply(myDF$ArrDelay,myDF$Origin,mean,na.rm=TRUE)))
print(tapply(myDF$Distance,myDF$Dest,mean,na.rm=TRUE)))
print(tapply(myDF$Distance,myDF$Dest,mean,na.rm=TRUE))
print(sort(tapply(myDF$Distance,myDF$Dest,mean,na.rm=TRUE),decreasing=TRUE)
print(sort(tapply(myDF$Distance,myDF$Dest,mean,na.rm=TRUE),decreasing=TRUE))
print(sort(tapply(myDF$ArrDelay,myDF$Dest,mean,na.rm=TRUE),decreasing=TRUE))
print(sort(tapply(myDF$ArrDelay,myDF$DayOfWeek,mean,na.rm=TRUE),decreasing=TRUE))
plot(tapply(myDF$ArrDelay,myDF$DayOfWeek,mean,na.rm=TRUE),decreasing=TRUE)
plot(tapply(MyOrigins$ArrDelay,MyOrigins$DayOfWeek,mean,na.rm=TRUE),decreasing=TRUE)
print(sort(tapply(MyOrigins$ArrDelay,MyOrigins$DayOfWeek,mean,na.rm=TRUE),decreasing=TRUE))
table(myDF$Month)
print(sort(tapply(myDF$DepDelay,myDF$DayOfWeek,mean,na.rm=TRUE),decreasing=TRUE))
print(sort(tapply(myDF$DepDelay,myDF$UniqueCarrier,mean,na.rm=TRUE),decreasing=TRUE))
mydates<-paste(myDF$DayofMonth,myDF$Month,myDF$Year,sep = "/")
print(sort(tapply(myDF$ArrDelay, mydates, mean,na.rm=TRUE)))
print(sort(tapply(MyOrigins$ArrDelay, mydates, mean,na.rm=TRUE)))
MyDates<-paste(MyOrigins$DayofMonth,MyOrigins$Month,MyOrigins$Year,sep="/")
print(sort(tapply(MyOrigins$ArrDelay, MyDates, mean,na.rm=TRUE)))
